單台相機校正

In [ ]:
#編號1
import cv2
import numpy as np
import glob

# 定義棋盤格的大小
chessboard_size = (9, 6)  
square_size = 2.5  # 棋盤格單位長度

# 準備3D世界座標點（位於XY平面）
objp = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2) * square_size

# 儲存對應的3D世界座標與2D影像座標
obj_points1 = []  # 3D座標點
img_points1 = []  # 2D影像座標點

# 讀取影像 
images1 = glob.glob("patternphoto/camera_computer/1/*.jpg") 

for fname in images1:
    img1 = cv2.imread(fname)
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

    # 偵測棋盤格角點
    ret, corners = cv2.findChessboardCorners(gray1, chessboard_size, None)

    if ret:
        obj_points1.append(objp)
        img_points1.append(corners)

        # 繪製角點以確認偵測正確
        img1=cv2.drawChessboardCorners(img1, chessboard_size, corners, ret)
        cv2.imshow('Chessboard Corners', img1)
        #plt.show()
        cv2.waitKey(500)

cv2.destroyAllWindows()


In [48]:
# 進行相機校正
ret1, camera_matrix1, dist_coeffs1, rvecs1, tvecs1 = cv2.calibrateCamera(obj_points1, img_points1, gray1.shape[::-1], None, None)

# 顯示結果
print("編號1:")
print("相機內參矩陣 (Camera Matrix):\n", camera_matrix1)
print("畸變係數 (Distortion Coefficients):\n", dist_coeffs1)
print(f"RMS 重投影誤差: {ret1:.4f} 像素")

編號1:
相機內參矩陣 (Camera Matrix):
 [[2.00360408e+03 0.00000000e+00 9.25242081e+02]
 [0.00000000e+00 1.50411453e+03 5.29417906e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
畸變係數 (Distortion Coefficients):
 [[ 4.63559055e-03 -5.89700965e-01  5.09270412e-05  2.11691149e-03
   1.88317468e+00]]
RMS 重投影誤差: 0.9870 像素


In [ ]:
#編號2

import cv2
import numpy as np
import glob

chessboard_size = (9, 6)  
square_size = 2.5  

objp = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2) * square_size

obj_points2 = [] 
img_points2 = []  


images2 = glob.glob("patternphoto/camera_computer/2/*.jpg") 

for fname in images2:
    img2 = cv2.imread(fname)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray2, chessboard_size, None)

    if ret:
        obj_points2.append(objp)
        img_points2.append(corners)

        img2=cv2.drawChessboardCorners(img2, chessboard_size, corners, ret)
        cv2.imshow('Chessboard Corners', img2)
        cv2.waitKey(500)

cv2.destroyAllWindows()


In [ ]:

ret2, camera_matrix2, dist_coeffs2, rvecs2, tvecs2 = cv2.calibrateCamera(obj_points2, img_points2, gray2.shape[::-1], None, None)

print("編號2:")
print("相機內參矩陣 (Camera Matrix):\n", camera_matrix2)
print("畸變係數 (Distortion Coefficients):\n", dist_coeffs2)
print(f"RMS 重投影誤差: {ret2:.4f} 像素")

編號2:
相機內參矩陣 (Camera Matrix):
 [[1.97386030e+03 0.00000000e+00 8.99068057e+02]
 [0.00000000e+00 1.48037743e+03 5.62805759e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
畸變係數 (Distortion Coefficients):
 [[ 1.44373320e-01 -2.83192799e+00 -3.66737222e-03  4.73604559e-04
   1.23743308e+01]]
RMS 重投影誤差: 0.9833 像素


In [ ]:
#編號3

import cv2
import numpy as np
import glob

chessboard_size = (9, 6)  
square_size = 2.5  

objp = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
objp[:, :2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2) * square_size

obj_points3 = []  
img_points3 = []  

images3 = glob.glob("patternphoto/camera_computer/3/*.jpg") 

for fname in images3:
    img3 = cv2.imread(fname)
    gray3 = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
  

    ret, corners = cv2.findChessboardCorners(gray3, chessboard_size, None)

    if ret:
        obj_points3.append(objp)
        img_points3.append(corners)

        img3=cv2.drawChessboardCorners(img3, chessboard_size, corners, ret)
        cv2.imshow('Chessboard Corners', img3)
        cv2.waitKey(500)

cv2.destroyAllWindows()


In [ ]:

ret3, camera_matrix3, dist_coeffs3, rvecs3, tvecs3 = cv2.calibrateCamera(obj_points3, img_points3, gray3.shape[::-1], None, None)

print("編號3:")
print("相機內參矩陣 (Camera Matrix):\n", camera_matrix3)
print("畸變係數 (Distortion Coefficients):\n", dist_coeffs3)
print(f"RMS 重投影誤差: {ret3:.4f} 像素")

編號3:
相機內參矩陣 (Camera Matrix):
 [[1.98807867e+03 0.00000000e+00 9.54628263e+02]
 [0.00000000e+00 1.48698973e+03 5.75289864e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
畸變係數 (Distortion Coefficients):
 [[ 4.87647738e-02 -1.42206998e+00  2.63301440e-04  3.75294232e-03
   5.23169573e+00]]
RMS 重投影誤差: 0.9512 像素
